### ISSUE TITLE
vite build error

### ISSUE THREAD

**Issue by wgsheng06** [aresyy/rollup-plugin-nearley#2]
报错大致如下：

plugin: 'vite:worker-import-meta-url',
Waiting for the debugger to disconnect...
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Parse error @:13:70
    at parse$e (file:///D:/Codes/Iflytek/offline3.0/fviz-web-offline/node_modules/.pnpm/vite@4.5.5_@types+node@18.19.55_less@4.2.0/node_modules/vite/dist/node/chunks/dep-b2890f90.js:16497:355)
    at Object.transform (file:///D:/Codes/Iflytek/offline3.0/fviz-web-offline/node_modules/.pnpm/vite@4.5.5_@types+node@18.19.55_less@4.2.0/node_modules/vite/dist/node/chunks/dep-b2890f90.js:46653:27) {

vite 执行buildImportAnalysisPlugin函数时候，没有经过插件就直接处理.ne文件导致的报错，不知道改如何处理了

**Comment by aln8** [comment]
sorry for the late, try new version 2.1.0
